[package]
name = "fccore"
version = "0.0.1"
authors = [ "Blake Loring <blake_l@parsed.uk>" ]

[dependencies]
time = "*"
rustc-serialize = "*"
rand = "*"
simplelog = { git = "https://github.com/jawline/SimpleLog.git" }

[dependencies.protocol]
path = "../../Protocol/"